shell script for osx, now in pkg

diff --git a/etc/redis-stack-server b/etc/redis-stack-server
--- a/etc/redis-stack-server
+++ b/etc/redis-stack-server
@@ -1,9 +1,35 @@
 #!/bin/sh
 
-#### placeholder for redis-stack-server script
-BASEDIR=/opt/redis-stack
-cd ${BASEDIR}
+OS=`uname -s`
+ARCH=`uname -m`
 
+#### placeholder for redis-stack-server script
+if [ ${OS} == "Darwin" ]; then
+    if [ ${ARCH} == "x86_64" ]; then
+        BASEDIR=/usr/local/
+        REDIS_DATA_DIR=${BASEDIR}/var/db/redis
+    else
+        BASEDIR=/opt/redis-stack
+        REDIS_DATA_DIR=${BASEDIR}/var/db/redis
+    fi
+else {
+    # TODO add proper linux support
+    BASEDIR=/opt/redis-stack
+    REDIS_DATA_DIR=/var/db/redis
+}
+fi
+
+if [ ! -d ${REDIS_DATA_DIR} ]; then
+    mkdir -p ${REDIS_DATA_DIR}
+    if [ $? -ne 0 ]; then
+        echo "Unable to write to ${REDIS_DATA_DIR} as the current user. Exiting."
+        exit 1
+    fi
+fi
+
+MODULEDIR=${BASEDIR}/lib
+
+cd ${BASEDIR}
 CMD=${BASEDIR}/bin/redis-server
 if [ -f $1 ]; then
     CONFFILE=$1
@@ -12,15 +38,17 @@ fi
 
 ${CMD} \
 ${CONFFILE} -- \
+--dir ${REDIS_DATA_DIR} \
 --protected-mode no \
---loadmodule /opt/redis-stack/lib/redisearch.so \
+--daemonize no \
+--loadmodule ${BASEDIR}/lib/redisearch.so \
 ${REDISEARCH_ARGS} \
---loadmodule /opt/redis-stack/lib/redisgraph.so \
+--loadmodule ${BASEDIR}/lib/redisgraph.so \
 ${REDISGRAPH_ARGS} \
---loadmodule /opt/redis-stack/lib/redistimeseries.so \
+--loadmodule ${BASEDIR}/lib/redistimeseries.so \
 ${REDISTIMESERIES_ARGS} \
---loadmodule /opt/redis-stack/lib/rejson.so \
+--loadmodule ${BASEDIR}/lib/rejson.so \
 ${REJSON_ARGS} \
---loadmodule /opt/redis-stack/lib/redisbloom.so \
+--loadmodule ${BASEDIR}/lib/redisbloom.so \
 ${REDISBLOOM_ARGS} \
 S*
